language: python
python:
  - "3.6"
install: pip install -r scrape-requirements.txt
before_script:
  - npm install -g n
  - n 12.18.1
  - npm install -g serverless
script:
  - make
notifications:
  email:
    recipients:
      - tdhopper@gmail.com
    on_success: change
    on_failure: always
